services:
  apt-cacher:
    container_name: apt-cacher
    build:
      context: util/apt-cacher
    ports:
      - "3142:3142"
    restart: unless-stopped

  # Our registry which we push test resources to.
  registry:
    image: registry:3
    ports:
      - "5000:5000"
    restart: unless-stopped

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse_user
      POSTGRES_PASSWORD: concourse_pass
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U concourse_user -d concourse"]
      interval: 3s
      timeout: 3s
      retries: 5

  web:
    image: concourse/concourse
    command: web
    links: [ db ]
    depends_on: [ db ]
    ports: [ "8080:8080" ]
    volumes: [ "./keys/web:/concourse-keys" ]
    restart: unless-stopped
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test

      CONCOURSE_ENABLE_PIPELINE_INSTANCES: "true"
      CONCOURSE_ENABLE_ACROSS_STEP: "true"
      CONCOURSE_ENABLE_RESOURCE_CAUSALITY: "true"
    extra_hosts:
      - "apt-cacher:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  worker:
    image: concourse/concourse
    restart: unless-stopped
    command: worker
    privileged: true
    depends_on: [ web ]
    volumes: [ "./keys/worker:/concourse-keys" ]
    links: [ web ]
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_RUNTIME: "containerd"
      # allow to reach the registry container
      CONCOURSE_CONTAINERD_ALLOW_HOST_ACCESS: "true"
      CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE: "true"
    extra_hosts:
      - "apt-cacher:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
